In [1]:
import numpy as np

In [2]:
#(a)
a1 = np.array([1,1,-1,-1,-1])
a2 = np.array([1,1,1,1,1])
a3 = np.array([1,-1,1,-1,1])

q1 = a1 / np.linalg.norm(a1)
w2 = a2 - np.dot(a2, q1) * q1
q2 = w2 / np.linalg.norm(w2)
w3 = a3 - np.dot(a3, q1) * q1 - np.dot(a3, q2) * q2
q3 = w3 / np.linalg.norm(w3)

print(f"q1 = {q1}")
print(f"q2 = {q2}")
print(f"q3 = {q3}")

q1 = [ 0.4472136  0.4472136 -0.4472136 -0.4472136 -0.4472136]
q2 = [0.54772256 0.54772256 0.36514837 0.36514837 0.36514837]
q3 = [ 0.46291005 -0.46291005  0.3086067  -0.6172134   0.3086067 ]


In [22]:
#(b)
A = np.vstack((a1,a2,a3)).astype(float).T
M, N = A.shape
Q = A.copy()
R = np.zeros((N, N))
for j in range(N):
    for i in range(j):
        R[i, j] = np.dot(A[:,j], Q[:,i])
        Q[:, j] -= R[i, j] * Q[:, i]
    
    
    norm_wj = np.linalg.norm(Q[:,j])
    R[j, j] = norm_wj
    Q[:, j] /= norm_wj
    
print(f"Q = {Q}")
print(f"R = {R}")
print(f"QR = {np.dot(Q, R)}")

Q = [[ 0.4472136   0.54772256  0.46291005]
 [ 0.4472136   0.54772256 -0.46291005]
 [-0.4472136   0.36514837  0.3086067 ]
 [-0.4472136   0.36514837 -0.6172134 ]
 [-0.4472136   0.36514837  0.3086067 ]]
R = [[ 2.23606798 -0.4472136  -0.4472136 ]
 [ 0.          2.19089023  0.36514837]
 [ 0.          0.          2.1602469 ]]
QR = [[ 1.  1.  1.]
 [ 1.  1. -1.]
 [-1.  1.  1.]
 [-1.  1. -1.]
 [-1.  1.  1.]]
